= Experiments with Confluent Schema Registry

== Building the code

Building the code using gradle:

```shell
./gradlew build
```

Potentially, you might need to update gradle first:

```shell
gradle wrapper
```

== Running the code

First, start the docker environment:

```shell
docker compose up -d
```
Create a new topic:

```shell
docker compose exec broker kafka-topics --bootstrap-server broker:9092 --topic measurements --create
```


Register the schema by running this command in the current subfolder:

```shell
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"namespace\": \"models.avro\", \"type\": \"record\", \"name\": \"SimpleValue\", \"fields\": [ {\"name\": \"theName\", \"type\": \"string\"}, {\"name\": \"theValue\", \"type\": \"string\"}]}"}' \
http://localhost:8081/subjects/measurements-value/versions
```

Run producer with gradle:

```shell
./gradlew -p java-producer run
```

Run consumer with:

```shell
./gradlew -p java-consumer run
```

Run a consumer compiled with an older version of the avro schema to see if it can successfully consume the messages produced with the newer schema:

```shell
./gradlew -p java-consumer-old-avro run
```

Now register an updated version of the schema which is NOT compatible in any way.


== Helpful tools

=== Schema Registry


Get all known versions:

```shell
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions
```

Inspect a specific version (here: version 1):

```shell
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions/1
```

Soft delete a specific version:

```shell
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions/1
```

Permanently delete a specific version (you need to soft delete first):

```shell
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions/1?permanent=true
```


=== CLI Consumer

Read messages via CLI tools, using standard console consumer:

```shell
docker compose exec kafka kafka-console-consumer --bootstrap-server broker:9092 --topic measurements --from-beginning
```

Read messages via avro console consumer:

```shell
docker compose exec kafka kafka-avro-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=http://localhost:8081 --topic measurements --from-beginning
```

You might want to delete the topic to start fresh between tests:

```shell
docker compose exec kafka  kafka-topics --bootstrap-server broker:9092 --delete --topic measurements
```

Alternatively, if you just want to consume the same messages again with the Java consumer, just reset the consumer groups offset:

```shell
docker compose exec kafka kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --reset-offsets --to-earliest --topic measurements --execute
```

You can view the offsets by running:

```shell
docker compose exec kafka kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --describe
```

== Experimenting

== Shutting down, deleting containers

```shell
docker compose down -v
```

== Development

Check for dependency updates in each of the sub projects like this:

```shell
./gradlew -P java-producer dependencyUpdates -Drevision=release
```

Upgrade the dependency manually.

For upgrading the gradle version, you can use this:

```shell
gradle wrapper --gradle-version <gradle version>
```
