= Experiments with Confluent Schema Registry

== Building the code

Building the code using gradle:

```shell
./gradlew build
```

Potentially, you might need to update gradle first:

```shell
gradle wrapper
```

== Running the code

First, start the docker environment:

```shell
docker compose up -d
```
Create a new topic:

```shell
docker compose exec broker kafka-topics --bootstrap-server broker:9092 --topic measurements --create
```

For convenience, a tiny shell script is provided which helps converting avro schema files to a format usable directly with `curl`.
Convert the two schemas and save them to variables in your shell like this (tested with bash):

```shell
export MEASUREMENT1_SCHEMA=$(./convert-avro-schema.sh avro/measurement-v1.avsc)
export MEASUREMENT2_SCHEMA=$(./convert-avro-schema.sh avro/measurement-v2.avsc)
```

Register the first version of our schema by running:

```shell
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data "$MEASUREMENT1_SCHEMA" \
http://localhost:8081/subjects/measurements-value/versions
```

Show all schema versions:

```bash
curl schema-registry:8081/subjects/measurements-value/versions
```

Get schema with specific version (here: version 1):

```bash
curl -s schema-registry:8081/subjects/measurements-value/versions/1/schema | jq .
```


Run producer with gradle:

```shell
./gradlew -p producer-schema-v1 run
```

Run consumer with:

```shell
./gradlew -p java-consumer run
```

Run a consumer compiled with an older version of the avro schema to see if it can successfully consume the messages produced with the newer schema:

```shell
./gradlew -p java-consumer-old-avro run
```

Now register an updated version of the schema which is NOT compatible in any way.


== Helpful tools

=== Schema Registry


Get all known versions:

```shell
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions
```

Inspect a specific version (here: version 1):

```shell
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions/1
```

Soft delete a specific version:

```shell
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions/1
```

Permanently delete a specific version (you need to soft delete first):

```shell
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/measurements-value/versions/1?permanent=true
```


=== CLI Consumer

Read messages via CLI tools, using standard console consumer:

```shell
docker compose exec kafka kafka-console-consumer --bootstrap-server broker:9092 --topic measurements --from-beginning
```

Read messages via avro console consumer:

```shell
docker compose exec kafka kafka-avro-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=http://localhost:8081 --topic measurements --from-beginning
```

You might want to delete the topic to start fresh between tests:

```shell
docker compose exec kafka  kafka-topics --bootstrap-server broker:9092 --delete --topic measurements
```

Alternatively, if you just want to consume the same messages again with the Java consumer, just reset the consumer groups offset:

```shell
docker compose exec kafka kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --reset-offsets --to-earliest --topic measurements --execute
```

You can view the offsets by running:

```shell
docker compose exec kafka kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --describe
```

== Experimenting

== Shutting down, deleting containers

```shell
docker compose down -v
```

== Development

Check for dependency updates in each of the sub projects like this:

```shell
./gradlew -P java-producer dependencyUpdates -Drevision=release
```

Upgrade the dependency manually.

For upgrading the gradle version, you can use this:

```shell
gradle wrapper --gradle-version <gradle version>
```
