= Experiments with Confluent Schema Registry

== Building the code

Building the code using gradle:

```bash
./gradlew build
```

Potentially, you might need to update gradle first:

```bash
gradle wrapper
```

== Running the code

First, start the docker environment:

```bash
docker compose up -d
```

First, set the compatilibity level of our subject to "FORWARD_TRANSITIVE":

```bash
curl -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"compatibility": "FORWARD_TRANSITIVE"}' \
http://localhost:8081/config/topic-value
```


Register the schema:

```bash
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"namespace\": \"models.avro\", \"type\": \"record\", \"name\": \"SimpleValue\", \"fields\": [ {\"name\": \"theName\", \"type\": \"string\"}, {\"name\": \"theValue\", \"type\": \"string\"}]}"}' \
http://localhost:8081/subjects/topic-value/versions
```

Try to register an updated version of the schema, which is NOT forward compatible (should fail!):

```bash
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"namespace\": \"models.avro\", \"type\": \"record\", \"name\": \"SimpleValue\", \"fields\": [ {\"name\": \"theName\", \"type\": \"string\"}]}"}]}"}' \
http://localhost:8081/subjects/topic-value/versions
```


Register an updated version of the schema, which is forward compatible (thus should in theory allow an older consumer to read it). We just add a another value:

```bash
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"namespace\": \"models.avro\", \"type\": \"record\", \"name\": \"SimpleValue\", \"fields\": [ {\"name\": \"theName\", \"type\": \"string\"}, {\"name\": \"theValue\", \"type\": \"string\"}, {\"name\": \"theNewName\", \"type\": \"string\"}]}"}' \
http://localhost:8081/subjects/topic-value/versions
```

Run producer with gradle:

```bash
./gradlew -p java-producer run
```

Run consumer with:

```bash
./gradlew -p java-consumer run
```

Run a consumer compiled with an older version of the avro schema to see if it can successfully consume the messages produced with the newer schema:

```bash
./gradlew -p java-consumer-old-avro run
```

Notice how the consumer will work, but does not output the extra field `theNewName` which was added when updating the schema.


== Helpful tools

=== Schema Registry


Get all known versions:

```bash
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions
```

Inspect a specific version (here: version 1):

```bash
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions/1
```

Soft delete a specific version:

```bash
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions/1
```

Permanently delete a specific version (you need to soft delete first):

```bash
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions/1?permanent=true
```


=== CLI Consumer

Read messages via CLI tools, using standard console consumer:

```bash
docker compose exec broker kafka-console-consumer --bootstrap-server broker:9092 --topic topic --from-beginning
```

Read messages via avro console consumer:

```bash
docker compose exec schema-registry kafka-avro-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=http://localhost:8081 --topic topic --from-beginning
```

You might want to delete the topic to start fresh between tests:

```bash
docker compose exec broker  kafka-topics --bootstrap-server broker:9092 --delete --topic topic
```

Alternatively, if you just want to consume the same messages again with the Java consumer, just reset the consumer groups offset:

```bash
docker compose exec broker kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --reset-offsets --to-earliest --topic topic --execute
```

You can view the offsets by running:

```bash
docker compose exec broker kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --describe
```

== Experimenting

== Development

Check for dependency updates in each of the sub projects like this:

```bash
./gradlew -P java-producer dependencyUpdates -Drevision=release
```

Upgrade the dependency manually.

For upgrading the gradle version, you can use this:

```bash
gradle wrapper --gradle-version <gradle version>
```


== Shutting down, deleting containers

```bash
docker compose down -v
```

